### ISSUE TITLE
Even with #32, phar file is not valid

### ISSUE THREAD

**Issue by ferrastas** [beechit/json-to-code-climate-subset-converter#34]
```
DOCKER_BUILDKIT=0 docker build . -t converter
Sending build context to Docker daemon  911.4kB
Step 1/15 : ARG PHP_VERSION=7.4
Step 2/15 : FROM php:${PHP_VERSION}-cli-alpine as base
 ---> bbe514846e2b
Step 3/15 : FROM base as builder
 ---> bbe514846e2b
Step 4/15 : WORKDIR /project
 ---> Using cache
 ---> a8ab270d077f
Step 5/15 : COPY --from=composer:2 /usr/bin/composer /usr/bin/composer
 ---> Using cache
 ---> bd9a95c52810
Step 6/15 : RUN composer global config minimum-stability dev     && composer global config prefer-stable true
 ---> Using cache
 ---> 8f7301396e18
Step 7/15 : RUN composer global require --prefer-dist humbug/box
 ---> Using cache
 ---> 4fc4e4d28c7f
Step 8/15 : COPY composer.* ./
 ---> Using cache
 ---> 46b716e7247c
Step 9/15 : RUN composer install --prefer-dist --no-dev --no-progress --no-suggest
 ---> Using cache
 ---> a230c26587ef
Step 10/15 : COPY . .
 ---> 8a660224b7ce
Step 11/15 : RUN $HOME/.composer/vendor/bin/box compile
 ---> Running in 19159880e123

    ____
   / __ )____  _  __
  / __  / __ \| |/_/
 / /_/ / /_/ />  <
/_____/\____/_/|_|


Box version 3.13.0@275b091

 // Loading the configuration file "/project/box.json".

🔨  Building the PHAR "/project/bin/converter.phar"

? No compactor to register
? Adding main file: /project/bin/converter
? Adding requirements checker
? Adding binary files
    > No file found
? Auto-discover files? No
? Exclude dev files? Yes
? Adding files
    > 505 file(s)
? Generating new stub
  - Using shebang line: #!/usr/bin/env php
  - Using banner:
    > Generated by Humbug Box 3.13.0@275b091.
    >
    > @link https://github.com/humbug/box
? Dumping the Composer autoloader
? Removing the Composer dump artefacts
? No compression
? Setting file permissions to 0755
* Done.

No recommendation found.
No warning found.

 // PHAR: 528 files (2.75MB)
 // You can inspect the generated PHAR with the "info" command.

 // Memory usage: 16.59MB (peak: 16.80MB), time: 1sec

Removing intermediate container 19159880e123
 ---> 13689b56e8bc
Step 12/15 : FROM base
 ---> bbe514846e2b
Step 13/15 : COPY --from=builder /project/bin/converter.phar /usr/bin/converter
 ---> 4c99904b161f
Step 14/15 : ENTRYPOINT ["/usr/bin/converter"]
 ---> Running in 25021924e42b
Removing intermediate container 25021924e42b
 ---> 74d4254b2476
Step 15/15 : CMD ["-h"]
 ---> Running in f9884a38de07
Removing intermediate container f9884a38de07
 ---> 99be348f3f8f
Successfully built 99be348f3f8f
Successfully tagged converter:latest

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
```

```
docker run -it converter

Warning: include(): Filename cannot be empty in phar:///usr/bin/converter/vendor/phlak/config/src/Loaders/Php.php on line 19

Warning: include(): Failed opening '' for inclusion (include_path='.:/usr/local/lib/php') in phar:///usr/bin/converter/vendor/phlak/config/src/Loaders/Php.php on line 19

Fatal error: Uncaught PHLAK\Config\Exceptions\InvalidFileException:  does not return a valid array in phar:///usr/bin/converter/vendor/phlak/config/src/Loaders/Php.php:22
Stack trace:
#0 phar:///usr/bin/converter/vendor/phlak/config/src/Config.php(221): PHLAK\Config\Loaders\Php->getArray()
#1 phar:///usr/bin/converter/vendor/phlak/config/src/Config.php(38): PHLAK\Config\Config->load('phar:///usr/bin...', NULL)
#2 phar:///usr/bin/converter/src/Factories/CommandFactory.php(21): PHLAK\Config\Config->__construct('phar:///usr/bin...')
#3 phar:///usr/bin/converter/bin/converter(34): BeechIt\JsonToCodeClimateSubsetConverter\Factories\CommandFactory->build('convert')
#4 /usr/bin/converter(14): require('phar:///usr/bin...')
#5 {main}
  thrown in phar:///usr/bin/converter/vendor/phlak/config/src/Loaders/Php.php on line 22
```

Seems that `PHLAK\Config\Config` cannot read from a phar directory, as using `file_get_contents` with the same path it prints the proper content.

**Comment by ttomdewit** [comment]
Closed via https://github.com/beechit/json-to-code-climate-subset-converter/pull/32
